name: Build

on:
  push:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest
    services:
      flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - 8191:8191
    
    steps:
      - name: Run
        run: |
          curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{ "cmd": "request.get", "url": "https://google.com", "maxTimeout": 60000 }'