name: Build

on:
  push:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Start Docker Container
        run: |
          docker network create custom_network
          docker run -d \
            --network=custom_network \
            --name=flaresolverr \
            -p 8191:8191 \
            -e LOG_LEVEL=info \
            flaresolverr/flaresolverr:latest

      - name: Wait for FlareSolverr to be ready
        run: |
          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:8191); do
              printf '.'
              sleep 1
          done

      - name: Execute Curl Command
        run: |
          curl -vvv -L -X POST 'http://127.0.0.1:8191/v1' -H 'Content-Type: application/json' --data-raw '{ "cmd": "request.get", "url": "https://www.op.gg/modes/aram", "maxTimeout": 60000 }'
