name: Build

on:
  push:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Run
        run: |
          curl -vvv -L -X POST 'http://0.0.0.0:8191/v1' -H 'Content-Type: application/json' --data-raw '{ "cmd": "request.get", "url": "https://www.op.gg/modes/aram", "maxTimeout": 60000 }'

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down